import { Eye, MapPin } from "lucide-react";

const statusStyles = { Available: "border-emerald-400/25 bg-emerald-400/10 text-emerald-300", Deployed: "border-blue-400/25 bg-blue-400/10 text-blue-300", "En Route": "border-orange-400/25 bg-orange-400/10 text-orange-300", Unavailable: "border-red-400/25 bg-red-400/10 text-red-300", Maintenance: "border-amber-400/25 bg-amber-400/10 text-amber-300" };
const conditionStyles = { Excellent: "text-emerald-300", Good: "text-cyan-300", "Needs Attention": "text-orange-300", Critical: "text-red-300" };

function ResourceTable({ resources, onView }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-255 border-collapse text-left"><thead className="border-b border-slate-800 bg-[#0d151c]"><tr>{["RESOURCE ID", "RESOURCE TYPE", "CURRENT LOCATION", "STATUS", "ASSIGNED ZONE", "CAPACITY", "CONDITION", "ETA", "ACTION"].map((heading) => <th key={heading} className="px-4 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-800/70">{resources.map((resource) => <tr key={resource.id} className="group border-l-2 border-transparent hover:border-cyan-400 hover:bg-slate-800/25"><td className="px-4 py-3 text-xs font-semibold text-slate-200">{resource.id}</td><td className="px-4 py-3 text-xs text-slate-400">{resource.type}</td><td className="px-4 py-3"><span className="flex items-center gap-1.5 text-xs text-slate-300"><MapPin size={13} className="text-slate-600" />{resource.location}</span></td><td className="px-4 py-3"><span className={`inline-flex whitespace-nowrap rounded border px-2 py-1 text-[10px] font-medium ${statusStyles[resource.status]}`}>{resource.status}</span></td><td className="px-4 py-3 text-xs text-slate-400">{resource.zone}</td><td className="px-4 py-3 text-xs text-slate-300">{resource.capacity}</td><td className={`px-4 py-3 text-xs font-medium ${conditionStyles[resource.condition]}`}>{resource.condition}</td><td className="px-4 py-3 text-xs text-slate-500">{resource.eta}</td><td className="px-4 py-3"><button type="button" onClick={() => onView(resource)} className="flex items-center gap-1.5 rounded border border-slate-700 px-2.5 py-1.5 text-[10px] font-bold tracking-[0.08em] text-slate-300 hover:border-cyan-400/40 hover:text-cyan-200"><Eye size={13} /> VIEW</button></td></tr>)}</tbody></table>{resources.length === 0 && <div className="px-4 py-12 text-center text-sm text-slate-500">No resources match the current filters.</div>}</div>;
}

export default ResourceTable;