import { Filter, RefreshCw, Search, X } from "lucide-react";
import { resourceConditions, resourceStatuses, resourceTypes, resourceZones } from "../../data/resources";

function ResourceFilters({ query, filters, onQueryChange, onFilterChange, onClear, onRefresh, refreshedAt, onAdd }) {
  const hasFilters = query || Object.values(filters).some((value) => value !== "All");
  const select = (label, key, options, className = "") => <select value={filters[key]} onChange={(event) => onFilterChange(key, event.target.value)} aria-label={label} className={`h-9 rounded border border-slate-700 bg-[#0d151c] px-2 text-xs text-slate-300 outline-none focus:border-cyan-400/60 ${className}`}><option>All</option>{options.map((item) => <option key={item}>{item}</option>)}</select>;
  return <section className="rounded-md border border-slate-800 bg-[#111b24] p-4"><div className="flex flex-wrap items-center gap-2"><label className="relative min-w-52.5 flex-1"><Search size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search resources" aria-label="Search resources" className="h-9 w-full rounded border border-slate-700 bg-[#0d151c] pl-9 pr-3 text-xs text-slate-200 outline-none placeholder:text-slate-600 focus:border-cyan-400/60" /></label><span className="flex items-center gap-1.5 text-slate-500"><Filter size={15} /><span className="hidden text-[10px] font-bold tracking-[0.12em] sm:inline">FILTERS</span></span>{select("Filter by resource type", "type", resourceTypes, "max-w-[150px]")}{select("Filter by status", "status", resourceStatuses)}{select("Filter by condition", "condition", resourceConditions)}{select("Filter by assigned zone", "zone", resourceZones, "max-w-[135px]")}{hasFilters && <button type="button" onClick={onClear} className="flex h-9 items-center gap-1 rounded px-2 text-[10px] font-bold text-slate-500 hover:bg-slate-800 hover:text-slate-200"><X size={13} /> CLEAR</button>}<button type="button" onClick={onRefresh} className="flex h-9 items-center gap-2 rounded border border-slate-700 px-3 text-xs text-slate-400 hover:bg-slate-800 hover:text-slate-100"><RefreshCw size={14} /><span className="hidden sm:inline">{refreshedAt ? "UPDATED" : "REFRESH"}</span></button><button type="button" onClick={onAdd} className="h-9 rounded bg-cyan-400 px-3 text-xs font-bold text-slate-950 hover:bg-cyan-300">+ ADD RESOURCE</button></div></section>;
}

export default ResourceFilters;