import { ArrowDown, ArrowUp, ArrowUpDown, Eye, MapPin } from "lucide-react";
import SeverityBadge from "./SeverityBadge";
import StatusBadge from "./StatusBadge";

function IncidentTable({ incidents, sort, onSort, onView }) {
  const sortIcon = (key) => sort.key !== key ? <ArrowUpDown size={12} /> : sort.direction === "asc" ? <ArrowUp size={12} /> : <ArrowDown size={12} />;
  const sortButton = (label, key) => <button type="button" onClick={() => onSort(key)} className="flex items-center gap-1 text-[10px] font-bold tracking-[0.12em] text-slate-500 hover:text-slate-200">{label}{sortIcon(key)}</button>;
  return <div className="overflow-x-auto"><table className="w-full min-w-245 border-collapse text-left"><thead className="border-b border-slate-800 bg-[#0d151c]"><tr><th className="px-4 py-3">{sortButton("INCIDENT ID", "id")}</th><th className="px-4 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500">LOCATION</th><th className="px-4 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500">TYPE</th><th className="px-4 py-3">{sortButton("AFFECTED PEOPLE", "affected")}</th><th className="px-4 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500">SEVERITY</th><th className="px-4 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500">RESOURCE NEED</th><th className="px-4 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500">STATUS</th><th className="px-4 py-3">{sortButton("REPORTED", "reportedMinutes")}</th><th className="px-4 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500">ACTION</th></tr></thead><tbody className="divide-y divide-slate-800/70">{incidents.map((incident) => <tr key={incident.id} className="group border-l-2 border-transparent hover:border-cyan-400 hover:bg-slate-800/25"><td className="px-4 py-3 text-xs font-semibold text-slate-200">{incident.id}</td><td className="px-4 py-3"><span className="flex items-center gap-1.5 text-xs text-slate-300"><MapPin size={13} className="text-slate-600" />{incident.location}</span></td><td className="px-4 py-3 text-xs text-slate-400">{incident.type}</td><td className="px-4 py-3 text-xs font-medium text-slate-200">{incident.affected.toLocaleString()}</td><td className="px-4 py-3"><SeverityBadge severity={incident.severity} /></td><td className="max-w-47.5 px-4 py-3 text-xs text-slate-400">{incident.resourceNeed}</td><td className="px-4 py-3"><StatusBadge status={incident.status} /></td><td className="px-4 py-3 text-xs text-slate-500">{incident.reported}</td><td className="px-4 py-3"><button type="button" onClick={() => onView(incident)} className="flex items-center gap-1.5 rounded border border-slate-700 px-2.5 py-1.5 text-[10px] font-bold tracking-[0.08em] text-slate-300 hover:border-cyan-400/40 hover:text-cyan-200"><Eye size={13} /> VIEW</button></td></tr>)}</tbody></table>{incidents.length === 0 && <div className="px-4 py-12 text-center text-sm text-slate-500">No incidents match the current filters.</div>}</div>;
}

export default IncidentTable;